# datasource
spring:
  datasource:
    url: jdbc:mysql://115.29.214.190:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: zmqa6b0ada1afafafjlafoeja322
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis映射文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定mapper.xml的文件
  type-aliases-package: com.wuming.mybatis.model # 此处声明model的包名，mapper.xml中则可以直接使用类名，更方便